name: Deployment Pipeline

on:
  push:
    branches: [main]
    paths:
      - "app.py"
      - "config.py"
      - "templates/**"
      - "static/**"
      - "Dockerfile"
      - "requirements.txt"
      - "docker-compose.yml"

      # Ignore these
      - "!README.md"
      - "!docs/**"
      - "!*.md"
      - "!.gitignore"
  jobs:
    deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Print environment variables
        run: echo "Deploying to STAGING environment"

      - name: Build Docker image (staging)
        run: docker build -t sakila-app:staging .

      - name: Run container (simulation)
        run: |
          docker run -d -p 5001:5000 sakila-app:staging
          sleep 5
          curl http://localhost:5001 || true

      - name: Deployment Summary
        run: |
          echo "## 🚀 Staging Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "Image: sakila-app:staging" >> $GITHUB_STEP_SUMMARY
          echo "Status: SUCCESS" >> $GITHUB_STEP_SUMMARY
      - name: Notify
        run: |
          echo "Slack notification: Deployment to staging successful"
      
      
    deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "🚀 Deploying to PRODUCTION..."

      - name: Create Release Tag
        id: tag
        run: echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify
        run: |
             echo "Slack notification: Deployment to staging successful"